# Header
menu:
  Home: /
  Archives: /archives
  WIKI: http://wiki.s-feng.com
  关于: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
